# Generated by Django 4.2.2 on 2024-05-24 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_payment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="сourse",
            new_name="course",
        ),
    ]
