# Generated by Django 4.2.2 on 2024-05-25 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_rename_сourse_payment_course"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="method",
            field=models.CharField(
                choices=[("MONEY", "Наличные"), ("BANK", "Перевод")],
                max_length=20,
                verbose_name="Способ оплаты",
            ),
        ),
    ]
